apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-um44
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0075-tenant/ci1t-830-0075-app/devfile-sample-um44@sha256:4ebc25433c6a34f25bb9afe449967921df39ddd70a51e9b422259ea93290c5c6
        name: my-nodejs
        resources: {}
status: {}
