apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-um44
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-um44
    app.kubernetes.io/part-of: ci1t-830-0075-app
  name: devfile-sample-um44
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-um44
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-um44
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0075-tenant/ci1t-830-0075-app/devfile-sample-um44@sha256:4ebc25433c6a34f25bb9afe449967921df39ddd70a51e9b422259ea93290c5c6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
